THIS NOTEBOOK DISCUSSES PREPROCESSING 

The idea of preprocessing is that you have the data that is not perfect to use rightaway with your model.
-> Some of the features might not be numerical.
-> some of the features might not be scaled yet.

In [2]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler #it is helpful for scaling data

In [3]:
X,y=load_iris(return_X_y=True)
X #we see the data is not scaled not normalized just the raw centimeter values

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
#now when we use it on testing data we dont fit it we just transform
X_test_scaled=scaler.transform(X_test)
''' 
why we do fit transform?
because the scaler has to learn certain values. what it does is it takes a sample and mean from the sample and the standard deviation or varience from sample
then it perform some calculations based on the values it learned from training data and the reason we use training data is because we are learning these values 
and doing the calculation
'''

' \nwhy we do fit transform?\nbecause the scaler has to learn certain values. what it does is it takes a sample and mean from the sample and the standard deviation or varience from sample\nthen it perform some calculations based on the values it learned from training data and the reason we use training data is because we are learning these values \nand doing the calculation\n'

STANDARD SCALER:
a standard scaler basically subtracts the mean from data and divides by the standard deviation. By doing this we zero center teh Data and and bring it to unit variance.

In [5]:
#doing same thing standard scaler does by numpy to prove:
import numpy as np
(X_train-np.mean(X_train,axis=0))/np.std(X_train,axis=0)

array([[-0.40394442,  0.93699124, -1.37245471, -1.29823377],
       [-1.12742697, -1.52681043, -0.23819462, -0.2500383 ],
       [-0.88626612, -1.30282846, -0.40833363, -0.11901386],
       [-0.40394442, -1.07884649,  0.38564843,  0.01201057],
       [ 0.80185982, -0.63088255,  0.49907444,  0.40508388],
       [ 1.88708364, -0.63088255,  1.3497695 ,  0.92918161],
       [-1.12742697,  0.04106336, -1.2590287 , -1.42925821],
       [ 1.04302067,  0.04106336,  0.55578744,  0.40508388],
       [ 1.16360109,  0.26504533,  1.2363435 ,  1.45327935],
       [-0.52452485,  0.71300927, -1.2590287 , -1.0361849 ],
       [-1.00684654,  0.4890273 , -1.3157417 , -1.29823377],
       [-0.76568569,  2.28088307, -1.2590287 , -1.42925821],
       [ 0.56069897,  0.4890273 ,  0.55578744,  0.53610831],
       [ 1.40476194,  0.26504533,  0.55578744,  0.27405944],
       [ 1.64592279,  1.16097321,  1.3497695 ,  1.71532822],
       [-1.12742697, -1.30282846,  0.44236143,  0.66713275],
       [ 0.07837728, -0.

MIN-MAX SCALING: you press all values to be between 0-1


In [6]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [7]:
#doing same thing min-max scaler does by numpy to prove:
import numpy as np
X_min=np.min(X_train,axis=0)
X_max=np.max(X_train,axis=0)
(X_train - X_min) / (X_max - X_min)

array([[0.33333333, 0.625     , 0.05084746, 0.04166667],
       [0.16666667, 0.16666667, 0.38983051, 0.375     ],
       [0.22222222, 0.20833333, 0.33898305, 0.41666667],
       [0.33333333, 0.25      , 0.57627119, 0.45833333],
       [0.61111111, 0.33333333, 0.61016949, 0.58333333],
       [0.86111111, 0.33333333, 0.86440678, 0.75      ],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.66666667, 0.45833333, 0.62711864, 0.58333333],
       [0.69444444, 0.5       , 0.83050847, 0.91666667],
       [0.30555556, 0.58333333, 0.08474576, 0.125     ],
       [0.19444444, 0.54166667, 0.06779661, 0.04166667],
       [0.25      , 0.875     , 0.08474576, 0.        ],
       [0.55555556, 0.54166667, 0.62711864, 0.625     ],
       [0.75      , 0.5       , 0.62711864, 0.54166667],
       [0.80555556, 0.66666667, 0.86440678, 1.        ],
       [0.16666667, 0.20833333, 0.59322034, 0.66666667],
       [0.44444444, 0.41666667, 0.54237288, 0.58333333],
       [0.22222222, 0.54166667,